### PR TITLE
token classification test

### PR DESCRIPTION
**Pull request by hemangjoshi37a**
Tried to create notebook in examples folder for token classification problem. Please help me develop this.

### CODE REVIEW

**Comment by xrsrke** [comment]
@hemangjoshi37a the code is so mess!! what is the `instruct` module?

image

**Comment by hemangjoshi37a** [comment]
@xrsrke 
I have removed the unneccesary code. Can you please recheck?

**Comment by xrsrke** [comment]
@hemangjoshi37a your code is so mess! there're lines that have errors!!

**Comment by hemangjoshi37a** [comment]
I know. Can you help me solve that?

**Pull request closed without merging**
